name: First WorkFlow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first greeting
        run: echo "Hello World!"
      - name: print goodbye
        run: echo "Done-bye!"
      - name: print another sentence
        run: echo "Another sentence test"
    
